package com.example.zhipengzhuo.entrytask.database;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.zhipengzhuo.entrytask.model.LearningData;

import com.example.zhipengzhuo.entrytask.database.LearningDataDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig learningDataDaoConfig;

    private final LearningDataDao learningDataDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        learningDataDaoConfig = daoConfigMap.get(LearningDataDao.class).clone();
        learningDataDaoConfig.initIdentityScope(type);

        learningDataDao = new LearningDataDao(learningDataDaoConfig, this);

        registerDao(LearningData.class, learningDataDao);
    }
    
    public void clear() {
        learningDataDaoConfig.clearIdentityScope();
    }

    public LearningDataDao getLearningDataDao() {
        return learningDataDao;
    }

}
